name: currencii
description: Currency Converter 4 Travelers

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.4.0+5

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  function_tree: ^0.9.1
  get_it: ^7.6.7
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/data/

  fonts:
      - family: NotoEmoji
        fonts:
          - asset: assets/fonts/NotoColorEmoji.ttf
            weight: 400