// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0V-2VCQYnjv0PdA49wIaztEGRPlHT628',
    appId: '1:740788789159:web:3e4f75733c10d934c5e082',
    messagingSenderId: '740788789159',
    projectId: 'currencii-app',
    authDomain: 'currencii-app.firebaseapp.com',
    storageBucket: 'currencii-app.appspot.com',
    measurementId: 'G-48KQ402JGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJTdWT8CVxPu_JpcOESkadG-M6J-3yx0w',
    appId: '1:740788789159:android:93c3c9c4cf062c63c5e082',
    messagingSenderId: '740788789159',
    projectId: 'currencii-app',
    storageBucket: 'currencii-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaFHLS9iBZuzmUzzwgsLOH2DJsX-Plr5M',
    appId: '1:740788789159:ios:aef6ba837de63f7ec5e082',
    messagingSenderId: '740788789159',
    projectId: 'currencii-app',
    storageBucket: 'currencii-app.appspot.com',
    iosBundleId: 'com.example.currencyConverter',
  );
}
